title: JJBA
email: jjba@protonmail.ch
description: >- # this means to ignore newlines until "baseurl:"
  Unix, engineering, hacking. Enrich yourself with knowledge and discover things that might be impressive and interesting in this tech blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://averageflow.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  averageflow

#paginate: 5


#minima:
#  skin: dark

# Build settings
#theme: minima
#jekyll-seo
plugins:
  - jekyll-feed
  - jekyll-paginate


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
